
module.exports = {
  STOCKS: [
    "RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK",
    "SBIN","ITC","LT","AXISBANK","KOTAKBANK",
    "HCLTECH","WIPRO","BHARTIARTL","HINDUNILVR",
    "TATASTEEL","JSWSTEEL","MARUTI","BAJFINANCE"
  ],
  TP: 0.02,
  SL: 0.01,
  MAX_TRADES: 5
};
